# Generated by Django 3.0.2 on 2020-02-16 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourhoodwatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='masterkey',
            new_name='masterneighbourhood',
        ),
        migrations.RemoveField(
            model_name='business',
            name='neighbourhood',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='city',
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business',
            field=models.ManyToManyField(to='neighbourhoodwatch.Business'),
        ),
        migrations.AddField(
            model_name='post',
            name='masterpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
