# Generated by Django 3.0.2 on 2020-02-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodwatch', '0002_auto_20200216_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
