# Generated by Django 3.0.2 on 2020-02-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodwatch', '0004_neighbourhood_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
