# Generated by Django 3.0.2 on 2020-02-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodwatch', '0005_business_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='business',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodwatch.Business'),
        ),
    ]
