# Generated by Django 3.0.2 on 2020-02-20 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourhoodwatch', '0006_auto_20200220_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='masterneighbourhood',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='recommended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
