# Generated by Django 3.0.2 on 2020-02-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodwatch', '0008_auto_20200221_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='business',
        ),
        migrations.AddField(
            model_name='business',
            name='neighbourhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourhoodwatch.Neighbourhood'),
        ),
    ]
