# Generated by Django 3.0.2 on 2020-02-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhoodwatch', '0009_auto_20200224_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
